# Generated by Django 3.0.5 on 2020-04-28 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverP', models.IntegerField()),
                ('senderP', models.IntegerField()),
                ('published', models.BooleanField(default=False)),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('diameter', models.SmallIntegerField()),
                ('delta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[(1, 'bitcoin'), (2, 'etherium'), (3, 'z-coin')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[(1, 'bitcoin'), (2, 'etherium'), (3, 'z-coin')], max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=256)),
                ('path_len', models.SmallIntegerField(default=1)),
                ('locked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencies', models.ManyToManyField(to='account.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed', models.BooleanField(default=False)),
                ('contracts', models.ManyToManyField(to='account.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Escrow'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hashes',
            field=models.ManyToManyField(to='account.Hash'),
        ),
        migrations.AddField(
            model_name='contract',
            name='secrets',
            field=models.ManyToManyField(to='account.Secrets'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('receiverP', 'senderP')},
        ),
    ]
